### ISSUE TITLE
For Help to build and run the project

### ISSUE THREAD

**Issue by pigozj** [usnistgov/psc-ns3#12]
I am the new to use github and your project . I have downloaded the project named 'psc-dev' ,but I dont konw how to do the next step, can anybody tell me or give me some suggestions? Thank you very very much.

**Comment by tomhenderson** [comment]
Hi, this project is a variant of the mainline ns-3.29 release.  The first step may be to work through the ns-3 tutorial posted here:  https://www.nsnam.org/releases/ns-3-29/documentation/

The tutorial has a 'Getting Started' section that should get you running.

Once you understand the tutorial, then you can move on to trying the examples that are described in the documentation PDF you will find in the psc-ns3 directory (called ns3-psc-documentation.pdf).

**Comment by pigozj** [comment]
> Hi, this project is a variant of the mainline ns-3.29 release. The first step may be to work through the ns-3 tutorial posted here: https://www.nsnam.org/releases/ns-3-29/documentation/
> 
> The tutorial has a 'Getting Started' section that should get you running.
> 
> Once you understand the tutorial, then you can move on to trying the examples that are described in the documentation PDF you will find in the psc-ns3 directory (called ns3-psc-documentation.pdf).

Thank you for your reply, I am working on it.
