### ISSUE TITLE
Constant values of SINR

### ISSUE THREAD

**Issue by SAAFISalwa** [usnistgov/psc-ns3#14]
Hello,

I am trying to visualize the SINR values vs. time. In the "SlRxPhyStats.txt", SINR values are constant. Is it because this is the average value at each instant? and if this is the case, how can I get the non-average values ?

Thanks in advance.

**Comment by richardrouil** [comment]
The values are usually constant if the UE is not moving and the propagation model does have small scale fading enabled.

**Comment by SAAFISalwa** [comment]
Thanks for your reply.
