### ISSUE TITLE
LTE Sidelink vs. NR Sidelink

### ISSUE THREAD

**Issue by SAAFISalwa** [usnistgov/psc-ns3#16]
Hello,

Apart from the supported frequency bands and bandwidths, are there major differences in the ns-3 implementations of Sidelink between LENA and 5G LENA modules?

If yes, are you planning to implement the NR Sidelink feature on 5G LENA module also?

Thanks a lot,
Salwa.

**Comment by richardrouil** [comment]
There are major differences between the LTE sidelink mode 1 and 2 (which we implemented) and NR sidelink. NR sidelink reuses some of the concepts of LTE sidelink mode 3 and 4 (e.g. sensing), but also has many new features that are not supported in LTE sidelink, like feedback channel and quality of service. 3GPP TR 37.985 provides a good description of each sidelink.

With regards to implementation in ns-3, NIST has awarded a grant to CTTC on "Modeling, Simulation, and Performance Evaluation of NR V2X" which includes the development of NR Sidelink (http://www.cttc.es/awardednistgrant/).

**Comment by SAAFISalwa** [comment]
Thanks a lot for your reply Richard!

Concerning the "Modeling, Simulation, and Performance Evaluation of NR V2X" project, are there published papers or Github repositories that include its initial results? or it's still in an early-stage of development?

**Comment by richardrouil** [comment]
It is still in early-stage of development. Announcements will be made once there is any publicly available code/papers.

**Comment by SAAFISalwa** [comment]
Thank you !

**Comment by hanghoo** [comment]
> Thanks a lot for your reply Richard!
> 
> Concerning the "Modeling, Simulation, and Performance Evaluation of NR V2X" project, are there published papers or Github repositories that include its initial results? or it's still in an early-stage of development?

Hello Salwa,

Do you have any progress about the 5G NR simulation?

Best regards,
Hang

**Comment by ibrahimth** [comment]
Hi there, 
I'm confused about the channel model in releases 16 and 17. For example, In 3GPP TR 37.885, we can see that it is clearly defined the channel model for the NR V2V sidelink. While for the V2B, they are referred to TR 38.901. So, I would like to know what is the channel model for NR V2I sidelink.
I appreciate any help you can provide.
