### ISSUE TITLE
Channel Model for NR V2X sidelink

### ISSUE THREAD

**Issue by ibrahimth** [usnistgov/psc-ns3#22]
Hi there, 
I'm confused about the channel model in releases 16 and 17. For example, In 3GPP TR 37.885, we can see that it is clearly defined the channel model for the NR V2V sidelink. While for the V2B, they are referred to TR 38.901. So, I would like to know what is the channel model for NR V2I sidelink.
I appreciate any help you can provide.

_Originally posted by @ibrahimth in https://github.com/usnistgov/psc-ns3/issues/16#issuecomment-1006156783_

**Comment by tomhenderson** [comment]
I am not aware of a recommended V2I channel model; I suppose you should consider whether such infrastructure most closely resembles something like a cell tower (perhaps reuse V2B model) or something road-side (perhaps reuse V2R model).
