### ISSUE TITLE
licensing terms

### ISSUE THREAD

**Issue by tkphd** [usnistgov/psc-ns3#4]
Please replace the GPLv2 text in LICENSE with the approved [statement](https://www.nist.gov/director/copyright-fair-use-and-licensing-statements-srd-data-and-software#software).
Please also replace (or delete) the similar statement in README.

Thank you.

**Comment by richardrouil** [comment]
Only portions of the software have been modified, either by adding new files or modifying existing ones. For example, https://github.com/usnistgov/psc-ns3/blob/d2d-ns-3.22/src/nist/model/nist-sl-pool.h includes a NIST disclaimer, though an old one apparently. 
We cannot simple change the entire software license, but the LICENSE file was modified to add a statement for this version. The readme file is not changed.

Also, we have been working on an updated version of the code that will contain all appropriate licenses as discussed with NIST counsel several months ago. We hope to publish it within the next couple of weeks.

**Comment by tkphd** [comment]
That makes perfect sense, thanks for clarifying. My objection to your license is withdrawn.
