### ISSUE TITLE
Build failure with python bindings enabled

### ISSUE THREAD

**Issue by rahulsn84** [usnistgov/psc-ns3#5]
Hi, 
I am trying to build the psc-ns3 code using ns-allinone-3.28.1 base with python bindings enabled. When I give the ./waf command to build I get the errors mentioned below. Any idea on what is wrong here? Do i need to build the python bindings again for lte module ? 

**compilation logs below:**
[1910/2061] Compiling src/wifi/model/supported-rates.cc
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteAsSapProvider__tp_init__0(PyNs3LteAsSapProvider*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:38054:61: error: invalid new-expression of abstract class type ‘PyNs3LteAsSapProvider__PythonHelper’
         self->obj = new PyNs3LteAsSapProvider__PythonHelper();
                                                             ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:4919:7: note:   because the following virtual functions are pure within ‘PyNs3LteAsSapProvider__PythonHelper’:
 class PyNs3LteAsSapProvider__PythonHelper : public ns3::LteAsSapProvider
       ^
In file included from ./ns3/epc-ue-nas.h:27:0,
                 from ./ns3/lte-module.h:28,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-as-sap.h:94:16: note: 	virtual void ns3::LteAsSapProvider::SendData(ns3::Ptr<ns3::Packet>, uint32_t)
   virtual void SendData (Ptr<Packet> packet, uint32_t group) = 0;
                ^
./ns3/lte-as-sap.h:110:16: note: 	virtual void ns3::LteAsSapProvider::ActivateSidelinkRadioBearer(uint32_t, bool, bool)
   virtual void ActivateSidelinkRadioBearer (uint32_t group, bool tx, bool rx) = 0;
                ^
./ns3/lte-as-sap.h:117:16: note: 	virtual void ns3::LteAsSapProvider::DeactivateSidelinkRadioBearer(uint32_t)
   virtual void DeactivateSidelinkRadioBearer (uint32_t group) = 0;
                ^
./ns3/lte-as-sap.h:124:16: note: 	virtual void ns3::LteAsSapProvider::AddDiscoveryApps(std::list<unsigned int>, bool)
   virtual void AddDiscoveryApps (std::list<uint32_t> apps, bool rxtx) = 0;
                ^
./ns3/lte-as-sap.h:131:16: note: 	virtual void ns3::LteAsSapProvider::RemoveDiscoveryApps(std::list<unsigned int>, bool)
   virtual void RemoveDiscoveryApps (std::list<uint32_t> apps, bool rxtx) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteAsSapProvider__tp_init__1(PyNs3LteAsSapProvider*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:38082:99: error: invalid new-expression of abstract class type ‘PyNs3LteAsSapProvider__PythonHelper’
         self->obj = new PyNs3LteAsSapProvider__PythonHelper(*((PyNs3LteAsSapProvider *) arg0)->obj);
                                                                                                   ^
src/lte/bindings/ns3module.cc: In function ‘PyObject* _wrap_PyNs3LteAsSapProvider_SendData(PyNs3LteAsSapProvider*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:38135:67: error: call of overloaded ‘SendData(ns3::Ptr<ns3::Packet>, int&)’ is ambiguous
     self->obj->SendData(ns3::Ptr< ns3::Packet  > (packet_ptr), bid);
                                                                   ^
src/lte/bindings/ns3module.cc:38135:67: note: candidates are:
In file included from ./ns3/epc-ue-nas.h:27:0,
                 from ./ns3/lte-module.h:28,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-as-sap.h:86:16: note: virtual void ns3::LteAsSapProvider::SendData(ns3::Ptr<ns3::Packet>, uint8_t)
   virtual void SendData (Ptr<Packet> packet, uint8_t bid) = 0;
                ^
./ns3/lte-as-sap.h:94:16: note: virtual void ns3::LteAsSapProvider::SendData(ns3::Ptr<ns3::Packet>, uint32_t)
   virtual void SendData (Ptr<Packet> packet, uint32_t group) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteAsSapUser__tp_init__0(PyNs3LteAsSapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:38573:57: error: invalid new-expression of abstract class type ‘PyNs3LteAsSapUser__PythonHelper’
         self->obj = new PyNs3LteAsSapUser__PythonHelper();
                                                         ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:4970:7: note:   because the following virtual functions are pure within ‘PyNs3LteAsSapUser__PythonHelper’:
 class PyNs3LteAsSapUser__PythonHelper : public ns3::LteAsSapUser
       ^
In file included from ./ns3/epc-ue-nas.h:27:0,
                 from ./ns3/lte-module.h:28,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-as-sap.h:180:16: note: 	virtual void ns3::LteAsSapUser::NotifySidelinkRadioBearerActivated(uint32_t)
   virtual void NotifySidelinkRadioBearerActivated (uint32_t group) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteAsSapUser__tp_init__1(PyNs3LteAsSapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:38601:91: error: invalid new-expression of abstract class type ‘PyNs3LteAsSapUser__PythonHelper’
         self->obj = new PyNs3LteAsSapUser__PythonHelper(*((PyNs3LteAsSapUser *) arg0)->obj);
                                                                                           ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUeCmacSapUser__tp_init__0(PyNs3LteUeCmacSapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:77317:61: error: invalid new-expression of abstract class type ‘PyNs3LteUeCmacSapUser__PythonHelper’
         self->obj = new PyNs3LteUeCmacSapUser__PythonHelper();
                                                             ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:6982:7: note:   because the following virtual functions are pure within ‘PyNs3LteUeCmacSapUser__PythonHelper’:
 class PyNs3LteUeCmacSapUser__PythonHelper : public ns3::LteUeCmacSapUser
       ^
In file included from ./ns3/lte-ue-rrc.h:30:0,
                 from ./ns3/lte-helper.h:49,
                 from ./ns3/lte-3gpp-hex-grid-enb-topology-helper.h:39,
                 from ./ns3/lte-module.h:41,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-ue-cmac-sap.h:256:16: note: 	virtual void ns3::LteUeCmacSapUser::NotifySidelinkReception(uint8_t, uint32_t, uint32_t)
   virtual void NotifySidelinkReception (uint8_t lcId, uint32_t srcL2Id, uint32_t dstL2Id) = 0;
                ^
./ns3/lte-ue-cmac-sap.h:261:16: note: 	virtual void ns3::LteUeCmacSapUser::NotifyMacHasSlDataToSend()
   virtual void NotifyMacHasSlDataToSend () = 0;
                ^
./ns3/lte-ue-cmac-sap.h:265:16: note: 	virtual void ns3::LteUeCmacSapUser::NotifyMacHasNoSlDataToSend()
   virtual void NotifyMacHasNoSlDataToSend () = 0;
                ^
./ns3/lte-ue-cmac-sap.h:272:16: note: 	virtual void ns3::LteUeCmacSapUser::NotifyDiscoveryReception(ns3::Ptr<ns3::LteControlMessage>)
   virtual void NotifyDiscoveryReception (Ptr<LteControlMessage> msg) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUeCmacSapUser__tp_init__1(PyNs3LteUeCmacSapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:77345:99: error: invalid new-expression of abstract class type ‘PyNs3LteUeCmacSapUser__PythonHelper’
         self->obj = new PyNs3LteUeCmacSapUser__PythonHelper(*((PyNs3LteUeCmacSapUser *) arg0)->obj);
                                                                                                   ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUeCphySapProvider__tp_init__0(PyNs3LteUeCphySapProvider*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:78391:65: error: invalid new-expression of abstract class type ‘PyNs3LteUeCphySapProvider__PythonHelper’
         self->obj = new PyNs3LteUeCphySapProvider__PythonHelper();
                                                                 ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:7038:7: note:   because the following virtual functions are pure within ‘PyNs3LteUeCphySapProvider__PythonHelper’:
 class PyNs3LteUeCphySapProvider__PythonHelper : public ns3::LteUeCphySapProvider
       ^
In file included from ./ns3/lte-ue-phy.h:33:0,
                 from ./ns3/component-carrier-ue.h:29,
                 from ./ns3/lte-module.h:14,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-ue-cphy-sap.h:154:16: note: 	virtual void ns3::LteUeCphySapProvider::SetSlDiscTxPool(ns3::Ptr<ns3::SidelinkTxDiscResourcePool>)
   virtual void SetSlDiscTxPool (Ptr<SidelinkTxDiscResourcePool> pool) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:160:16: note: 	virtual void ns3::LteUeCphySapProvider::SetSlDiscRxPools(std::list<ns3::Ptr<ns3::SidelinkRxDiscResourcePool> >)
   virtual void SetSlDiscRxPools (std::list<Ptr<SidelinkRxDiscResourcePool> > pools) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:165:16: note: 	virtual void ns3::LteUeCphySapProvider::RemoveSlDiscTxPool()
   virtual void RemoveSlDiscTxPool () = 0;
                ^
./ns3/lte-ue-cphy-sap.h:172:16: note: 	virtual void ns3::LteUeCphySapProvider::SetSlCommTxPool(ns3::Ptr<ns3::SidelinkTxCommResourcePool>)
   virtual void SetSlCommTxPool (Ptr<SidelinkTxCommResourcePool> pool) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:178:16: note: 	virtual void ns3::LteUeCphySapProvider::SetSlCommRxPools(std::list<ns3::Ptr<ns3::SidelinkRxCommResourcePool> >)
   virtual void SetSlCommRxPools (std::list<Ptr<SidelinkRxCommResourcePool> > pools) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:183:16: note: 	virtual void ns3::LteUeCphySapProvider::RemoveSlCommTxPool()
   virtual void RemoveSlCommTxPool () = 0;
                ^
./ns3/lte-ue-cphy-sap.h:189:16: note: 	virtual void ns3::LteUeCphySapProvider::AddSlDestination(uint32_t)
   virtual void AddSlDestination (uint32_t destination) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:195:16: note: 	virtual void ns3::LteUeCphySapProvider::RemoveSlDestination(uint32_t)
   virtual void RemoveSlDestination (uint32_t destination) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:201:16: note: 	virtual void ns3::LteUeCphySapProvider::SetSlssId(uint64_t)
   virtual void SetSlssId (uint64_t slssid) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:206:17: note: 	virtual void ns3::LteUeCphySapProvider::SendSlss(ns3::LteRrcSap::MasterInformationBlockSL)
    virtual void SendSlss (LteRrcSap::MasterInformationBlockSL mibSl) = 0;
                 ^
./ns3/lte-ue-cphy-sap.h:212:17: note: 	virtual void ns3::LteUeCphySapProvider::SynchronizeToSyncRef(ns3::LteRrcSap::MasterInformationBlockSL)
    virtual void SynchronizeToSyncRef (LteRrcSap::MasterInformationBlockSL mibSl) = 0;
                 ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUeCphySapProvider__tp_init__1(PyNs3LteUeCphySapProvider*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:78419:107: error: invalid new-expression of abstract class type ‘PyNs3LteUeCphySapProvider__PythonHelper’
         self->obj = new PyNs3LteUeCphySapProvider__PythonHelper(*((PyNs3LteUeCphySapProvider *) arg0)->obj);
                                                                                                           ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUeCphySapUser__tp_init__0(PyNs3LteUeCphySapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:79024:61: error: invalid new-expression of abstract class type ‘PyNs3LteUeCphySapUser__PythonHelper’
         self->obj = new PyNs3LteUeCphySapUser__PythonHelper();
                                                             ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:7099:7: note:   because the following virtual functions are pure within ‘PyNs3LteUeCphySapUser__PythonHelper’:
 class PyNs3LteUeCphySapUser__PythonHelper : public ns3::LteUeCphySapUser
       ^
In file included from ./ns3/lte-ue-phy.h:33:0,
                 from ./ns3/component-carrier-ue.h:29,
                 from ./ns3/lte-module.h:14,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-ue-cphy-sap.h:305:16: note: 	virtual void ns3::LteUeCphySapUser::ReportSlssMeasurements(ns3::LteUeCphySapUser::UeSlssMeasurementsParameters, uint64_t, uint16_t)
   virtual void ReportSlssMeasurements (LteUeCphySapUser::UeSlssMeasurementsParameters params,  uint64_t slssid, uint16_t offset) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:311:16: note: 	virtual void ns3::LteUeCphySapUser::ReportSubframeIndication(uint16_t, uint16_t)
   virtual void ReportSubframeIndication (uint16_t frameNo, uint16_t subFrameNo) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:316:16: note: 	virtual void ns3::LteUeCphySapUser::ReceiveMibSL(ns3::LteRrcSap::MasterInformationBlockSL)
   virtual void ReceiveMibSL (LteRrcSap::MasterInformationBlockSL mibSl) = 0;
                ^
./ns3/lte-ue-cphy-sap.h:324:16: note: 	virtual void ns3::LteUeCphySapUser::ReportChangeOfSyncRef(ns3::LteRrcSap::MasterInformationBlockSL, uint16_t, uint16_t)
   virtual void ReportChangeOfSyncRef (LteRrcSap::MasterInformationBlockSL mibSl, uint16_t frameNo, uint16_t subFrameNo) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUeCphySapUser__tp_init__1(PyNs3LteUeCphySapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:79052:99: error: invalid new-expression of abstract class type ‘PyNs3LteUeCphySapUser__PythonHelper’
         self->obj = new PyNs3LteUeCphySapUser__PythonHelper(*((PyNs3LteUeCphySapUser *) arg0)->obj);
                                                                                                   ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUePhySapProvider__tp_init__0(PyNs3LteUePhySapProvider*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:80009:64: error: invalid new-expression of abstract class type ‘PyNs3LteUePhySapProvider__PythonHelper’
         self->obj = new PyNs3LteUePhySapProvider__PythonHelper();
                                                                ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:7166:7: note:   because the following virtual functions are pure within ‘PyNs3LteUePhySapProvider__PythonHelper’:
 class PyNs3LteUePhySapProvider__PythonHelper : public ns3::LteUePhySapProvider
       ^
In file included from ./ns3/lte-ue-phy.h:32:0,
                 from ./ns3/component-carrier-ue.h:29,
                 from ./ns3/lte-module.h:14,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-ue-phy-sap.h:70:17: note: 	virtual void ns3::LteUePhySapProvider::AddDiscTxApps(std::list<unsigned int>)
    virtual void AddDiscTxApps (std::list<uint32_t> apps) = 0;
                 ^
./ns3/lte-ue-phy-sap.h:76:17: note: 	virtual void ns3::LteUePhySapProvider::AddDiscRxApps(std::list<unsigned int>)
    virtual void AddDiscRxApps (std::list<uint32_t> apps) = 0;
                 ^
./ns3/lte-ue-phy-sap.h:82:16: note: 	virtual void ns3::LteUePhySapProvider::SetDiscGrantInfo(uint8_t)
   virtual void SetDiscGrantInfo (uint8_t resPsdch) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUePhySapProvider__tp_init__1(PyNs3LteUePhySapProvider*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:80037:105: error: invalid new-expression of abstract class type ‘PyNs3LteUePhySapProvider__PythonHelper’
         self->obj = new PyNs3LteUePhySapProvider__PythonHelper(*((PyNs3LteUePhySapProvider *) arg0)->obj);
                                                                                                         ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUePhySapUser__tp_init__0(PyNs3LteUePhySapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:80454:60: error: invalid new-expression of abstract class type ‘PyNs3LteUePhySapUser__PythonHelper’
         self->obj = new PyNs3LteUePhySapUser__PythonHelper();
                                                            ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:7211:7: note:   because the following virtual functions are pure within ‘PyNs3LteUePhySapUser__PythonHelper’:
 class PyNs3LteUePhySapUser__PythonHelper : public ns3::LteUePhySapUser
       ^
In file included from ./ns3/lte-ue-phy.h:32:0,
                 from ./ns3/component-carrier-ue.h:29,
                 from ./ns3/lte-module.h:14,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/lte-ue-phy-sap.h:126:17: note: 	virtual void ns3::LteUePhySapUser::NotifyChangeOfTiming(uint32_t, uint32_t)
    virtual void NotifyChangeOfTiming (uint32_t frameNo, uint32_t subframeNo) = 0;
                 ^
./ns3/lte-ue-phy-sap.h:131:16: note: 	virtual void ns3::LteUePhySapUser::NotifySidelinkEnabled()
   virtual void NotifySidelinkEnabled () = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3LteUePhySapUser__tp_init__1(PyNs3LteUePhySapUser*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:80482:97: error: invalid new-expression of abstract class type ‘PyNs3LteUePhySapUser__PythonHelper’
         self->obj = new PyNs3LteUePhySapUser__PythonHelper(*((PyNs3LteUePhySapUser *) arg0)->obj);
                                                                                                 ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3EpcHelper__tp_init__0(PyNs3EpcHelper*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:109490:85: error: invalid new-expression of abstract class type ‘PyNs3EpcHelper__PythonHelper’
         self->obj = new PyNs3EpcHelper__PythonHelper(*((PyNs3EpcHelper *) arg0)->obj);
                                                                                     ^
In file included from src/lte/bindings/ns3module.cc:1:0:
src/lte/bindings/ns3module.h:8696:7: note:   because the following virtual functions are pure within ‘PyNs3EpcHelper__PythonHelper’:
 class PyNs3EpcHelper__PythonHelper : public ns3::EpcHelper
       ^
In file included from ./ns3/emu-epc-helper.h:32:0,
                 from ./ns3/lte-module.h:17,
                 from src/lte/bindings/ns3module.h:78,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/epc-helper.h:122:16: note: 	virtual void ns3::EpcHelper::ActivateSidelinkBearer(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::LteSlTft>)
   virtual void ActivateSidelinkBearer (Ptr<NetDevice> ueDevice, Ptr<LteSlTft> tft) = 0;
                ^
./ns3/epc-helper.h:130:16: note: 	virtual void ns3::EpcHelper::DeactivateSidelinkBearer(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::LteSlTft>)
   virtual void DeactivateSidelinkBearer (Ptr<NetDevice> ueDevice, Ptr<LteSlTft> tft) = 0;
                ^
./ns3/epc-helper.h:140:16: note: 	virtual void ns3::EpcHelper::StartDiscovery(ns3::Ptr<ns3::NetDevice>, std::list<unsigned int>, bool)
   virtual void StartDiscovery (Ptr<NetDevice> ueDevice, std::list<uint32_t> apps, bool rxtx) = 0;
                ^
./ns3/epc-helper.h:148:16: note: 	virtual void ns3::EpcHelper::StopDiscovery(ns3::Ptr<ns3::NetDevice>, std::list<unsigned int>, bool)
   virtual void StopDiscovery (Ptr<NetDevice> ueDevice, std::list<uint32_t> apps, bool rxtx) = 0;
                ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3EpcHelper__tp_init__1(PyNs3EpcHelper*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:109519:54: error: invalid new-expression of abstract class type ‘PyNs3EpcHelper__PythonHelper’
         self->obj = new PyNs3EpcHelper__PythonHelper();

**Output of ./waf configure:**

Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for cc version                  : 4.9.3 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for compilation flag -Wl,--soname=foo support : ok 
Checking for compilation flag -std=c++11 support       : ok 
Checking for program 'python'                          : /usr/bin/python 
Checking for python version                            : (2, 7, 12, 'final', 0) 
python-config                                          : /usr/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 
Checking for compilation flag -fvisibility=hidden support          : ok 
Checking for compilation flag -Wno-array-bounds support            : ok 
Checking for pybindgen location                                    : ../pybindgen-0.17.0.post58+ngcf00cc0 (guessed) 
Checking for python module 'pybindgen'                             : 0.17.0.post58+gcf00cc0 
Checking for pybindgen version                                     : 0.17.0.post58+gcf00cc0 
Checking for code snippet                                          : yes 
Checking for types uint64_t and unsigned long equivalence          : no 
Checking for code snippet                                          : no 
Checking for types uint64_t and unsigned long long equivalence     : yes 
Checking for the apidefs that can be used for Python bindings      : gcc-LP64 
Checking for internal GCC cxxabi                                   : complete 
Checking for python module 'pygccxml'                              : 1.9.1 
Checking for pygccxml version                                      : 1.9.1 
Checking for program 'castxml'                                     : /usr/bin/castxml 
Checking for castxml version                                       : 0.1 
Checking boost includes                                            : 1_58 
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for click location                                        : not found 
Checking for program 'pkg-config'                                  : /usr/bin/pkg-config 
Checking for 'gtk+-3.0' >= 3.0                                     : yes 
Checking for 'libxml-2.0' >= 2.7                                   : yes 
Checking for type uint128_t                                        : not found 
Checking for type __uint128_t                                      : yes 
Checking high precision implementation                             : 128-bit integer (default) 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for header sys/types.h                                    : yes 
Checking for header sys/stat.h                                     : yes 
Checking for header dirent.h                                       : yes 
Checking for header stdlib.h                                       : yes 
Checking for header signal.h                                       : yes 
Checking for header pthread.h                                      : yes 
Checking for header stdint.h                                       : yes 
Checking for header inttypes.h                                     : yes 
Checking for header sys/inttypes.h                                 : not found 
Checking for library rt                                            : yes 
Checking for header sys/ioctl.h                                    : yes 
Checking for header net/if.h                                       : yes 
Checking for header net/ethernet.h                                 : yes 
Checking for header linux/if_tun.h                                 : yes 
Checking for header netpacket/packet.h                             : yes 
Checking for NSC location                                          : not found 
Checking for OpenFlow location                                     : not found 
Checking for 'sqlite3'                                             : yes 
Checking for header linux/if_tun.h                                 : yes 
Checking for python module 'gi'                                    : 3.20.0 
Checking for python module 'gi.repository.GObject'                 : ok 
Checking for python module 'cairo'                                 : ok 
Checking for python module 'pygraphviz'                            : 1.3.1 
Checking for python module 'gi.repository.Gtk'                     : ok 
Checking for python module 'gi.repository.Gdk'                     : ok 
Checking for python module 'gi.repository.Pango'                   : ok 
Checking for python module 'gi.repository.GooCanvas'               : ok 
Checking for program 'sudo'                                        : /usr/bin/sudo 
Checking for program 'valgrind'                                    : /usr/bin/valgrind 
Checking for 'gsl'                                                 : yes 
python-config                                                      : /usr/bin/libgcrypt-config 
Checking for libgcrypt                                             : yes 
Checking for compilation flag -Wno-error=deprecated-d... support   : ok 
Checking for compilation flag -Wno-error=deprecated-d... support   : ok 
Checking for compilation flag -fstrict-aliasing support            : ok 
Checking for compilation flag -fstrict-aliasing support            : ok 
Checking for compilation flag -Wstrict-aliasing support            : ok 
Checking for compilation flag -Wstrict-aliasing support            : ok 
Checking for program 'doxygen'                                     : /usr/bin/doxygen 
---- Summary of optional NS-3 features:
Build profile                 : debug
Build directory               : 
BRITE Integration             : not enabled (BRITE not enabled (see option --with-brite))
DES Metrics event collection  : not enabled (defaults to disabled)
Emulation FdNetDevice         : enabled
Examples                      : not enabled (defaults to disabled)
File descriptor NetDevice     : enabled
GNU Scientific Library (GSL)  : enabled
Gcrypt library                : enabled
GtkConfigStore                : enabled
MPI Support                   : not enabled (option --enable-mpi not selected)
NS-3 Click Integration        : not enabled (nsclick not enabled (see option --with-nsclick))
NS-3 OpenFlow Integration     : not enabled (OpenFlow not enabled (see option --with-openflow))
Network Simulation Cradle     : not enabled (NSC not found (see option --with-nsc))
PlanetLab FdNetDevice         : not enabled (PlanetLab operating system not detected (see option --force-planetlab))
PyViz visualizer              : enabled
Python API Scanning Support   : enabled
Python Bindings               : enabled
Real Time Simulator           : enabled
SQlite stats data output      : enabled
Tap Bridge                    : enabled
Tap FdNetDevice               : enabled
Tests                         : not enabled (defaults to disabled)
Threading Primitives          : enabled
Use sudo to set suid bit      : not enabled (option --enable-sudo not selected)
XmlIo                         : enabled
'configure' finished successfully (3.121s)

**Comment by tomhenderson** [comment]
If you are trying to build the latest psc-ns3 code (which is aligned with ns-3.29) but on an ns-3.28 base, the Python bindings will not compile such as you described above because the C++ API is slightly different between the releases.  The options are to disable python from your build if you do not need to use the Python API (pass the '--disable-python' argument to Waf configure), or to move to ns-3.29, or to rescan the bindings if you install the bindings toolchain as described in the ns-3 tutorial/manual.

**Comment by tomhenderson** [comment]
Closing this because it is no longer applicable to the latest psc code or releases.

**Comment by Gowtham878** [comment]
It is enabling again during the build even after I disabled using waf... what should i do?

**Comment by tomhenderson** [comment]
Can you be more specific about exactly which version you are building, how you configured the build, and exactly what error you are having?
